import Link from "next/link";
import { randomUUID } from "node:crypto";
import { Activity, ArrowDownLeft, ArrowRight, ArrowUpRight, BadgeCheck, CircleHelp, Download, FileInput, Landmark, Layers3, LayoutDashboard, ListChecks, ReceiptText, ShieldCheck } from "lucide-react";
import type { Entity, Membership, Snapshot, Workspace } from "@/types/workspace";
import { agingBucket } from "@/lib/money";
import { Panel, Empty, Money, Badge } from "./ui";
import { ThemeButton } from "./theme-button";
import { MutationForm } from "./mutation-form";
import { ImportReview } from "./import-review";
const navigation = [
  { id: "overview", name: "Overview", icon: LayoutDashboard, description: "A clear view of your receivables and cash position." },
  { id: "receivables", name: "Receivables", icon: ReceiptText, description: "Investigate invoices, open balances, and collection states." },
  { id: "reconciliation", name: "Cash application", icon: Landmark, description: "Review bank direction, receipts, allocations, and residuals." },
  { id: "ecl", name: "ECL review", icon: ShieldCheck, description: "Review preserved measurement runs and their supporting assumptions." },
  { id: "approvals", name: "Approval inbox", icon: ListChecks, description: "Review the exact proposal and its financial impact before posting." },
  { id: "agents", name: "Agent activity", icon: Activity, description: "Follow recorded recommendations and execution outcomes." },
  { id: "imports", name: "Import review", icon: FileInput, description: "Validate source records and confirm an independent import review." },
  { id: "audit", name: "Audit explorer", icon: BadgeCheck, description: "Investigate recorded actors, operations, and financial evidence." },
] as const;
type Props = { memberships: Membership[]; entityOptions: Entity[]; data: Snapshot; view: Workspace; userId: string; email: string; message?: string };
export function FinanceWorkspace({ memberships, entityOptions, data, view, userId, email, message }: Props) {
  const tenant = memberships.find(row => row.tenant_id === data.tenant_id)!; const entity = entityOptions.find(row => row.id === data.entity_id)!;
  const active = navigation.find(row => row.id === view)!;
  const href = (target: string, page = 0) => `/?${new URLSearchParams({ tenant: data.tenant_id, entity: data.entity_id, view: target, page: String(page) })}`;
  const menu = <nav aria-label="Financial workspaces" className="space-y-1">{navigation.map(item => <Link href={href(item.id)} key={item.id} aria-current={item.id === view ? "page" : undefined}><item.icon size={18}/>{item.name}</Link>)}</nav>;
  return <div className="min-h-screen lg:grid lg:grid-cols-[240px_minmax(0,1fr)]">
    <aside className="rail hidden min-h-screen flex-col px-4 py-7 lg:flex"><div className="mb-10 flex items-center gap-3 px-3 text-xl font-semibold text-white"><Layers3 size={24}/><span>o2c<span className="ml-2 text-xs font-normal text-slate-300">finance</span></span></div><p className="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[.18em] text-slate-300">Operations</p>{menu}<div className="mt-auto border-t border-slate-500/40 px-3 pt-6"><ShieldCheck size={20} className="mb-3 text-violet-200"/><p className="text-sm font-medium text-white">Every decision, accountable.</p><p className="mt-2 text-xs leading-5 text-slate-300">Independent approval protects financial posting.</p></div></aside>
    <div className="min-w-0"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-line bg-surface px-6 py-4 lg:px-10"><div><p className="text-xs text-muted">{tenant.tenant_name}</p><p className="mt-1 font-semibold">{entity.name} <span className="ml-2 text-xs font-normal text-muted">AED</span></p></div><div className="flex items-center gap-3"><span className="hidden max-w-52 truncate text-xs text-muted sm:block" title={email}>{email} · {data.role}</span><ThemeButton/><form action="/api/auth" method="post"><input type="hidden" name="intent" value="logout"/><button className="button secondary">Sign out</button></form></div></header>
    <details className="rail px-6 py-4 lg:hidden"><summary className="font-medium">Workspaces · {active.name}</summary><div className="mt-4">{menu}</div></details>
    <main id="main" className="mx-auto max-w-[1500px] space-y-6 px-6 py-8 lg:px-10"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-xs font-medium uppercase tracking-[.16em] text-muted">Finance operations / {active.name}</p><h1 className="text-3xl font-semibold tracking-tight">{active.name}</h1><p className="mt-2 text-muted">{active.description}</p></div><Link className="button secondary" href={`/api/export?${new URLSearchParams({ tenant: data.tenant_id, entity: data.entity_id })}`}><Download size={16}/>Export first 50 invoices</Link></div>
    <div className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-line bg-surface px-5 py-4"><form method="get" className="flex flex-wrap items-end gap-3"><input type="hidden" name="view" value={view}/><label className="text-xs">Tenant<select name="tenant" defaultValue={data.tenant_id}>{memberships.map(row => <option key={row.tenant_id} value={row.tenant_id}>{row.tenant_name}</option>)}</select></label><label className="text-xs">Legal entity<select name="entity" defaultValue={data.entity_id}>{entityOptions.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><button className="button secondary">Apply scope</button></form><div className="text-xs leading-6 text-muted"><p><span className="font-medium text-ink">Verified snapshot</span> · {new Date(data.fetched_at).toLocaleString("en-AE", { timeZone: "Asia/Dubai" })} GST</p><p>Current balances · aging as of {data.as_of} · refresh to retrieve changes</p></div></div>
    {message && <div role="status" className={message === "confirmed" ? "rounded-lg bg-success-soft p-4 text-success" : "rounded-lg bg-warning-soft p-4 text-warning"}>{message === "confirmed" ? "The server confirmed this action. The workspace now shows its recorded state." : message === "conflict" ? "The records changed or this action conflicts with existing data. Review the refreshed evidence before creating a new proposal." : message === "forbidden" ? "This action requires an authorized independent reviewer. Check your role and the proposal maker." : message === "invalid_import" ? "The import failed validation. Correct all rejected rows before staging it again." : "The action could not be confirmed. Check its recorded state before retrying."}</div>}
    {view === "overview" && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      { label: "Open receivables", value: data.totals.open, help: "Posted invoice gross less posted allocations. All records in this entity." },
      { label: "Unapplied cash", value: data.totals.unapplied, help: "Posted receipts less posted invoice allocations. All records in this entity." },
      { label: "Gross receivables", value: data.totals.gross, help: "Gross amount of posted imported invoices. All records in this entity." },
      { label: "Approved ECL allowance", value: data.totals.allowance, help: "Latest approved preserved ECL run matching today's aging date. Unavailable until supplied." },
    ].map(item => <article key={item.label} className="rounded-xl border border-line bg-surface p-6 shadow-xs"><p className="text-sm text-muted">{item.label}</p><p className="mt-4 overflow-x-auto text-2xl font-semibold tracking-tight"><Money value={item.value}/></p><details className="mt-4 text-xs text-muted"><summary className="flex items-center gap-1"><CircleHelp size={12}/>Definition and source</summary><p className="mt-2 leading-5">{item.help} Source: authenticated database snapshot at {data.fetched_at}.</p></details></article>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><InvoiceTable data={data}/><Panel title="Review priorities" subtitle="Recorded work requiring attention"><div className="space-y-6 p-6"><div className="flex items-center justify-between"><p>Pending financial approvals</p><strong className="text-xl tabular-nums">{data.totals.pending_count}</strong></div><div className="flex items-center justify-between"><p>Imported invoice records</p><strong className="text-xl tabular-nums">{data.totals.invoice_count}</strong></div><Link className="button w-full" href={href("approvals")}>Open approval inbox<ArrowRight size={16}/></Link><p className="text-xs leading-5 text-muted">Bank lines become receipts only after independent approval and confirmed posting. Matching suggestions never settle invoices.</p></div></Panel></div></>}
    {view === "receivables" && <InvoiceTable data={data}/>}
    {view === "reconciliation" && <><Panel title="Bank statement lines" subtitle="Direction is preserved. Only incoming credits can become receipts.">{data.bank_lines.length ? <div className="overflow-auto"><table><caption className="sr-only">Bank statement records, current page</caption><thead><tr><th scope="col">Reference</th><th scope="col">Date</th><th scope="col">Direction</th><th scope="col" className="money">Amount AED</th><th scope="col">Receipt state</th></tr></thead><tbody>{data.bank_lines.map(row => <tr key={row.id}><td className="font-medium">{row.reference}</td><td>{row.booked_at}</td><td><span className="inline-flex items-center gap-2">{row.direction === "credit" ? <ArrowDownLeft size={14}/> : <ArrowUpRight size={14}/>}<Badge value={row.direction}/></span></td><td className="money"><Money value={row.amount}/></td><td><Badge value={row.posted ? "posted" : "unposted"}/></td></tr>)}</tbody></table></div> : <Empty title="No bank records on this page">Import a real bank statement to review incoming credits and outgoing debits.</Empty>}</Panel>
    <Panel title="Posted receipts and residuals" subtitle="Residual is unapplied cash; it is separate from unpaid invoices.">{data.receipts.length ? <div className="overflow-auto"><table><caption className="sr-only">Receipt records, current page</caption><thead><tr><th scope="col">Reference</th><th scope="col" className="money">Receipt AED</th><th scope="col" className="money">Residual AED</th></tr></thead><tbody>{data.receipts.map(row => <tr key={row.id}><td>{row.reference}</td><td className="money"><Money value={row.amount}/></td><td className="money"><Money value={row.residual}/></td></tr>)}</tbody></table></div> : <Empty title="No posted receipts on this page">An independently approved bank credit must be posted before it can be allocated.</Empty>}</Panel>
    {canMake(data) ? <div className="grid gap-6 xl:grid-cols-2"><Proposal data={data} kind="receipt"/><Proposal data={data} kind="allocation"/></div> : <p className="text-sm text-muted">Your role can review these records. A maker submits financial proposals.</p>}</>}
    {view === "approvals" && <Panel title="Financial proposals" subtitle="Approval and posting are separate. Evidence changes require a new proposal.">{data.approvals.length ? <div className="divide-y divide-line">{data.approvals.map(row => <article className="p-6" key={row.id}><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">{row.kind === "receipt" ? "Post incoming receipt" : "Allocate receipt to invoice"} · <Money value={row.amount}/></h3><Badge value={row.status}/></div><dl className="grid gap-3 text-sm sm:grid-cols-2"><Detail label="Proposal" value={`${row.id} · version ${row.version}`}/><Detail label="Maker" value={row.maker}/><Detail label="Independent checker" value={row.approver ?? "Awaiting review"}/><Detail label="Accounting impact" value={row.kind === "receipt" ? "Debit bank / credit unapplied cash" : "Debit unapplied cash / credit accounts receivable"}/><Detail label="Invoice / receipt" value={`${row.invoice_id ?? "—"} / ${row.receipt_id ?? "—"}`}/><Detail label="Bank line / customer" value={`${row.bank_line_id ?? "—"} / ${row.customer_id ?? "—"}`}/></dl><p className="mt-4 rounded-lg bg-surface-muted p-4 text-sm leading-6"><strong>Supporting evidence: </strong>{row.evidence}</p>
      {row.status === "pending" && canCheck(data) && row.maker !== userId && <div className="mt-5"><MutationForm><Scope data={data} view="approvals"/><input type="hidden" name="id" value={row.id}/><input type="hidden" name="version" value={row.version}/><Acknowledgement/><div className="flex gap-3"><button className="button" name="intent" value="approve">Approve this proposal</button><button className="button secondary" name="intent" value="reject">Reject proposal</button></div></MutationForm></div>}
      {row.status === "pending" && row.maker === userId && <p className="mt-4 text-xs text-muted">A different authorized user must approve this proposal.</p>}
      {row.status === "approved" && data.role !== "viewer" && <div className="mt-5"><MutationForm><Scope data={data} view="approvals"/><input type="hidden" name="id" value={row.id}/><input type="hidden" name="version" value={row.version}/><input type="hidden" name="intent" value="execute"/><Acknowledgement/><button className="button">Post approved {row.kind === "receipt" ? "receipt" : "allocation"}</button></MutationForm></div>}
    </article>)}</div> : <Empty title="No proposals on this page">A maker can submit a receipt or allocation from Cash application. No financial posting occurs without independent approval.</Empty>}</Panel>}
    {view === "ecl" && <Panel title="Preserved ECL measurement runs" subtitle="Model assumptions and approved results are supplied by your governed measurement process.">{data.ecl_runs.length ? <div className="divide-y divide-line">{data.ecl_runs.map(row => <article key={row.id} className="space-y-4 p-6"><div className="flex justify-between gap-4"><h3 className="font-semibold">Model {row.model_version} · {row.as_of}</h3><Badge value={row.status}/></div><p>Allowance: <Money value={row.allowance}/></p><p className="break-all text-sm text-muted">Exposure snapshot: {row.exposure_snapshot}</p><details><summary>Scenarios, weights, overlays, and lineage</summary><pre className="mt-3 overflow-auto rounded bg-surface-muted p-4 text-xs">{row.scenario}</pre></details></article>)}</div> : <Empty title="No preserved ECL runs on this page">Connect a governed ECL measurement process with frozen exposure, model version, scenarios, overlays, and approval evidence. No default loss rates or automatic provisions are applied.</Empty>}</Panel>}
    {view === "agents" && <Panel title="Recorded agent activity" subtitle="Execution is confirmed only when an authoritative domain operation is recorded.">{data.agent_runs.length ? <div className="overflow-auto"><table><caption className="sr-only">Agent execution records</caption><thead><tr><th scope="col">Agent</th><th scope="col">State</th><th scope="col">Domain operation</th><th scope="col">Updated</th></tr></thead><tbody>{data.agent_runs.map(row => <tr key={row.id}><td>{row.name}</td><td><Badge value={row.status}/></td><td className="break-all">{row.operation_id ?? "No posted operation"}</td><td>{row.updated_at}</td></tr>)}</tbody></table></div> : <Empty title="No agent activity on this page">No agent runtime is connected. Connect an authorized worker to record recommendations, approval requests, executions, and failures. Agent output cannot bypass financial controls.</Empty>}</Panel>}
    {view === "imports" && <div className="grid gap-6 xl:grid-cols-2"><Panel title="Validate a source file" subtitle="Stage first. An independent checker commits the exact preserved batch."><div className="p-6">{canMake(data) ? <ImportReview key={`${data.tenant_id}/${data.entity_id}`} tenant={data.tenant_id} entity={data.entity_id}/> : <p className="text-muted">A maker can upload and stage source files.</p>}</div></Panel><Panel title="Import batches" subtitle="Atomic commits: a conflict rolls back the entire batch.">{data.imports.length ? <div className="divide-y divide-line">{data.imports.map(row => <article key={row.id} className="space-y-3 p-6"><div className="flex justify-between gap-3"><h3 className="break-all font-semibold">{row.file_name}</h3><Badge value={row.status}/></div><p className="text-sm">{row.rows} records · <Money value={row.total}/></p><p className="break-all text-xs text-muted">{row.digest}</p><Link className="text-sm font-semibold text-primary" href={`/imports/${row.id}?${new URLSearchParams({ tenant: data.tenant_id, entity: data.entity_id })}`}>Review preserved rows and commit <ArrowRight className="inline" size={14}/></Link></article>)}</div> : <Empty title="No import batches on this page">Source files are validated and staged before they can affect operational records.</Empty>}</Panel></div>}
    {view === "audit" && <Panel title="Append-only audit events" subtitle="Financial proposals, decisions, import commits, and posting evidence.">{data.audit.length ? <div className="divide-y divide-line">{data.audit.map(row => <article key={row.id} className="p-6"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">{row.operation}</h3><time className="text-xs text-muted">{row.at}</time></div><p className="mt-2 break-all text-xs text-muted">Actor {row.actor} · Record {row.record_id}</p><details className="mt-3 text-sm"><summary>Inspect related evidence</summary><pre className="mt-3 overflow-auto rounded bg-surface-muted p-4 text-xs">{JSON.stringify(row.detail,null,2)}</pre></details></article>)}</div> : <Empty title="No audit events on this page">Confirmed financial and import operations append their evidence here.</Empty>}</Panel>}
    <div className="flex items-center justify-between gap-4 text-sm text-muted"><p>Page {data.page+1} · up to 50 records per workspace list · totals cover the full entity</p><div className="flex gap-3">{data.page>0 && <Link className="button secondary" href={href(view,data.page-1)}>Previous</Link>}{data.has_more && <Link className="button secondary" href={href(view,data.page+1)}>Next</Link>}</div></div>
    <footer className="flex flex-wrap justify-between gap-3 border-t border-line pt-6 text-xs text-muted"><span>O2C Finance Command Center</span><span>AED · Asia/Dubai · Server-confirmed operations</span></footer></main></div>
  </div>;
}
function canMake(data: Snapshot) { return ["maker","admin"].includes(data.role); }
function canCheck(data: Snapshot) { return ["approver","admin"].includes(data.role); }
function Scope({ data, view }: { data: Snapshot; view: string }) { return <><input type="hidden" name="tenant" value={data.tenant_id}/><input type="hidden" name="entity" value={data.entity_id}/><input type="hidden" name="view" value={view}/></>; }
function Acknowledgement() { return <label className="flex items-start gap-3 text-sm font-normal"><input required type="checkbox" name="acknowledge" value="yes"/><span>I reviewed the tenant, entity, AED amount, affected records, evidence, and accounting impact shown above.</span></label>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>; }
function InvoiceTable({ data }: { data: Snapshot }) { return <Panel title="Receivables ledger" subtitle="Lifecycle, settlement, dispute, and collections are tracked separately.">{data.invoices.length ? <div className="overflow-auto"><table><caption className="sr-only">Receivables current page; balances from posted allocations</caption><thead><tr><th scope="col">Invoice / customer</th><th scope="col" className="money">Open AED</th><th scope="col">Aging / due date</th><th scope="col">Lifecycle / settlement</th><th scope="col">Dispute / collection</th></tr></thead><tbody>{data.invoices.map(row => <tr key={row.id}><td><strong>{row.number}</strong><p className="mt-1 text-xs text-muted">{row.customer}</p></td><td className="money"><Money value={row.open}/><p className="mt-1 text-xs text-muted">Gross <Money value={row.gross}/></p></td><td>{agingBucket(row.due_date,data.as_of)}<p className="mt-1 text-xs text-muted">{row.due_date}</p></td><td><Badge value={row.lifecycle}/><p className="mt-2"><Badge value={row.settlement}/></p></td><td><Badge value={row.dispute}/><p className="mt-2"><Badge value={row.collection}/></p></td></tr>)}</tbody></table></div> : <Empty title="No receivables on this page">Import verified open invoices from your source system. Empty data stays empty; no sample balances are created.</Empty>}</Panel>; }
function Proposal({ data, kind }: { data: Snapshot; kind: "receipt" | "allocation" }) {
  const banks = data.bank_lines.filter(row => row.direction === "credit" && !row.posted); const receipts = data.receipts.filter(row => row.residual !== "0.00");
  return <Panel title={kind === "receipt" ? "Propose incoming receipt" : "Propose cash allocation"} subtitle={kind === "receipt" ? "Bank credit → unapplied cash. Approval required." : "Unapplied cash → invoice settlement. Approval required."}><div className="p-6"><MutationForm><Scope data={data} view="reconciliation"/><input type="hidden" name="id" value={randomUUID()}/><input type="hidden" name="intent" value="propose"/><input type="hidden" name="kind" value={kind}/>
    {kind === "receipt" ? <><label>Bank credit<select required name="bank" defaultValue=""><option value="" disabled>Select incoming credit</option>{banks.map(row => <option key={row.id} value={row.id}>{row.reference} · AED {row.amount}</option>)}</select></label><label>Customer<select required name="customer" defaultValue=""><option value="" disabled>Select customer</option>{data.customers.map(row => <option key={row.id} value={row.id}>{row.name} · {row.account}</option>)}</select></label></> : <><label>Posted receipt<select required name="receipt" defaultValue=""><option value="" disabled>Select receipt</option>{receipts.map(row => <option key={row.id} value={row.id}>{row.reference} · AED {row.residual} remaining</option>)}</select></label><label>Invoice<select required name="invoice" defaultValue=""><option value="" disabled>Select invoice</option>{data.invoices.filter(row => row.lifecycle === "posted" && row.open !== "0.00").map(row => <option key={row.id} value={row.id}>{row.number} · {row.customer} · AED {row.open}</option>)}</select></label></>}
    <label>Exact amount AED<input required name="amount" inputMode="decimal" pattern="(0|[1-9][0-9]{0,12})(\.[0-9]{1,2})?" placeholder="0.00"/></label><label>Supporting evidence<textarea required name="evidence" minLength={10} maxLength={2000} placeholder="Reference the statement, remittance, and reason for this proposal."/></label><p className="text-xs leading-5 text-muted">Selections are from the current page. The server validates ownership, direction, balances, and record versions.</p><button className="button" disabled={kind === "receipt" ? !banks.length || !data.customers.length : !receipts.length || !data.invoices.length}>Submit for approval</button>
  </MutationForm></div></Panel>;
}
